# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:

  # Update GitHub Actions workflow versions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot-actions"
    assignees:
      - "chrimaho"
    commit-message:
      prefix: "deps(actions): "

  # Update Python dependencies
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot-python"
    assignees:
      - "chrimaho"
    commit-message:
      prefix: "deps(pip): "
